[package]
name = "hc_time_index"
version = "0.1.0"
authors = ["jdeepee <joshuadparkin@gmail.com>"]
edition = "2018"
exclude = ["tests/*", "time-chunking.dna.workdir/*", "time-chunking.dna.gz", ".gitignore"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_time_index"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[dependencies]
hdk = "0.0.101-alpha.0"

#derive_more = "0"
serde = "1"
lazy_static = "*"
chrono = "0.4"
mut_static = "*"
permutation = "0.2.5"
thiserror = "1.0.24"
petgraph = "*"

[patch.crates-io]
hdk = { git = "https://github.com/holochain/holochain", rev="24ceb63bdea374d1936b723e1966caf2e55ebfdc", package="hdk"}
holo_hash = { git = "https://github.com/holochain/holochain", rev="24ceb63bdea374d1936b723e1966caf2e55ebfdc", package="holo_hash"}